### ISSUE TITLE
Colorbar not displayed properly in the Multiplot class

### ISSUE THREAD

**Issue by benedettaveronesi** [dmentipl/plonk#1]
### Describe the bug

When using the visualization.MultiPlot class, the colorbars are not displayed properly. There are two issues.
1. When using 'render_scale': 'log', the image is rendered correctly, but the colorbar remains linear. 
2. When choosing a shape different from (1 x N) or (N x 1), the colorbars of some subplots are not displayed at all. 

I am plotting a Phantom dump obtained with a one fluid multigrain simulation. 
This is part of the code I'm using for the multiplot: 

```
totdustfrac = np.zeros(1000000)

for s in range(0,5):
    grains = dump.header['grainsize'][s]*dump.header['udist']*10**(4) 
    dustfrac = dump.particles.arrays['dustfrac'][:,s]
    totdustfrac +=dump.particles.arrays['dustfrac'][:,s]

new_units = plonk.Units(length='au', mass='g', time='yr', density=1., velocity=1.0e5)
density = dump.density
density = dump.units.convert_quantity_to_new_units(density, 'density', new_units)

gas_density = density*(1.-totdustfrac)

options = list()
options.append({'render': gas_density,
                'render_scale': 'log',
                'extent': [-100,100,-100,100],
                'inclination': -65,
                'position_angle': -21,
                'normalize':False,
                'render_label': r'$\Sigma_{\rm gas}$ [g cm${}^{-2}$]',
                'integrated_z':plonk.constants.au,
               })

label_dust = [r'$\Sigma_{{\rm d},1.77\,\mu{\rm m}}$ [g cm${}^{-2}$]',
              r'$\Sigma_{{\rm d},5.56\,\mu{\rm m}}$ [g cm${}^{-2}$]',
              r'$\Sigma_{{\rm d},0.017\,{\rm mm}}$ [g cm${}^{-2}$]',
              r'$\Sigma_{{\rm d},0.054\,{\rm mm}}$ [g cm${}^{-2}$]',
              r'$\Sigma_{{\rm d},0.17\,{\rm mm}}$ [g cm${}^{-2}$]',
              r'$\Sigma_{{\rm d},0.54\,{\rm mm}}$ [g cm${}^{-2}$]',
              r'$\Sigma_{{\rm d},1.7 {\rm mm}}$ [g cm${}^{-2}$]']
    
    
for s in range(0,5):
    options.append({'render': density*dump.particles.arrays['dustfrac'][:,s],
                   'render_scale': 'log',
                   'extent': [-100,100,-100,100],
                   'inclination': -65,
                   'position_angle': -21,
                   'render_label': label_dust[s],
                   'font_size': 30, 
                    'normalize': False,
                    'integrated_z':plonk.constants.au,
                   })

    

multiplot = plonk.visualization.MultiPlot(
    dump,
    options,
    scale=7,
    shape=(3,2),
    axes_pad=0.7,
    cbar_mode='each',
    cbar_location='top',
    cbar_pad=0.2
)
```

### Expected behavior

NxM subplots, each with a colorbar in log scale. 

### Screenshots

![image](https://user-images.githubusercontent.com/48152197/63668148-991c0a00-c819-11e9-9e0f-4ec9bd51caf8.png)
Here you can see the (1x6) shape image, displaying all the colorbars, but not in log scale (the color rendering is performed properly in log). The (6x1) shape is behaving at the same way.

![Screen Shot 2019-08-26 at 15 50 53](https://user-images.githubusercontent.com/48152197/63668058-46dae900-c819-11e9-8695-457d6db0da95.png)
Here you can see the (2x3) shape image, not displaying properly the last colorbars. The colorbar is plotted only for the 0, the 3rd, 4th and 5th element. 

![image](https://user-images.githubusercontent.com/48152197/63668292-0a5bbd00-c81a-11e9-85f1-a419522aa7d4.png)
Here you can see the (3x2) shape image, not displaying properly the last colorbars. The colorbar is plotted only for the 0, the 2nd, 4th and 5th element. 

### Environment:

 - OS:  macOS 10.12.6
 - Python :  
                    - conda version : 4.7.11
                    - conda-build version : 3.17.8
                    - python version : 3.7.3.final.0
   (using Jupiter-lab)
 - Plonk version:  0.1.0

### Data source

 - SPH code: 
                     - Phantom, 
                      - version ->  Commit tag:     ok-20190328-44-g931253a
                                            Full commit ID: 931253a6f3b49940d2ec4d41e40a95c2e95e2d02 
                      - simulation performed with one fluid, multigrain setup.

**Comment by dmentipl** [comment]
Hi Benedetta, thanks for the bug report.

I don't think this should be too hard to fix.

I'll have a look this week.

**Comment by dmentipl** [comment]
For future reference, a more minimal bug report code snippet would be

```python
import plonk

dump = plonk.Dump('dump_00000.h5')

ndust = plonk.header['ndustsmall']

options = list()
options.append({'render': 'density'})

for idx in range(ndust):
    options.append({'render': dump.density * dump.particles.arrays['dustfrac'][:, idx]})

multiplot = plonk.visualization.MultiPlot(
    dump, options, shape=(3, 2), cbar_mode='each', cbar_location='top', cbar_pad=0.2
)
```

**Comment by dmentipl** [comment]
Hi @benedettaveronesi, sorry for taking so long to respond. I've been busy with a new release of Plonk (0.2.0). This release is a major overhaul of the internals of Plonk, and of the API.

I've actually removed MultiPlot from this release.

Having said that, I don't think it's too hard to do what you require:

```
snap = plonk.load_snap('path_to_your_file')
ndust = len(snap.properties['grain size'])

# Say ndust is 6
ncols = 3
nrows = 2

fig, axes = plt.subplots(nrows=nrows, ncols=ncols, sharex=True, sharey=True)
for idx in range(ndust):
    plonk.visualize.plot(
        scalar_data=snap['rho'] * snap['dustfrac'][:, idx],
        x_coordinate=snap['x'],
        y_coordinate=snap['y'],
        extent=(-100, 100, -100, 100),
        particle_mass=snap['m'],
        smoothing_length=snap['h'],
        axis=axes.ravel()[idx],
    )
```

Please, let me know if you have any further issues.
