### ISSUE TITLE
Plot dust density for one-fluid dump

### ISSUE THREAD

**Issue by benedettaveronesi** [dmentipl/plonk#22]
### Describe the bug

I tried different things in order to plot the dust density map in case of a one-fluid dump, without success. 

### To Reproduce

Steps to reproduce the behaviour:

1. Load data
```
filename = 'mdisc010racc01_00050.h5' 
snap = plonk.load_snap(filename)
```

2a. Gas visualisation (works fine):
```
viz = plonk.visualize.plot( snap=snap,
quantity='density',
extent=(-250, 250, -250, 250),
cmap='gist_heat')
```

2b. Dust visualisation (doesn't work):
```
viz = plonk.visualize.plot( snap=snap,
quantity='dust_density',
extent=(-250, 250, -250, 250),
cmap='gist_heat')
```

3. Since dust_density is in the `snap.available_arrays()` I was expecting to be able to plot it. Instead, I got this error:

ValueError: 2d quantity must be a vector quantity, e.g. "velocity".
For dust quantities, try appending the dust species number,
e.g. "dust_density_001".

I tried also using dust_density_001, without having success. 
I checked and apparently density and dust_density are respectively a line array and a column array. Thinking this could be the problem I converted the dust_density into a "line array", but also this doesn't work. 

I also tried defining a new snap quantity: 
`snap['dust_dens']=snap['density']*snap['dust_fraction']`
but it is incredibly slow and my notebook crashes. 

### Expected behaviour

I would expect to be able to plot the dust density map like the one plotted for the gas, when visualising a one-fluid dump. 

### Environment:

+ OS: e.g. macOS 10.12.6
+ Python: Python 3.7, Anaconda with conda 4.7.12, using Jupyter-lab notebook
+ Plonk version: 0.5.0

### Data source

+ SPH code: Phantom, commit version 931253a6f3b49940d2ec4d41e40a95c2e95e2d02, one-fluid method

**Comment by dmentipl** [comment]
Hi @benedettaveronesi, thanks very much for the bug report!

This certainly is a bug in Plonk. I've found where it is, and I will patch it today.

Just to be clear: in the code above under "2a. Gas visualisation (works fine):" you are *not* visualising the gas; you are visualising the total density including the dust.

To visualise the gas density you would do

```python
ax = plonk.visualise.plot(
    snap=snap,
    quantity='gas_density',
    extent=(-250, 250, -250, 250),
    cmap='gist_heat'
)
```

I hope that makes sense.

**Comment by dmentipl** [comment]
I've fixed this. I will make a new release (v0.5.3) as this is a major bug.

Please let me know if it works for you, or if you have any other issues.

Thanks again for raising this issue!
