### ISSUE TITLE
Incorrect temperature with phantom models with ieos=2

### ISSUE THREAD

**Issue by cpinte** [dmentipl/plonk#23]
### Describe the bug

Plonk does not appear to to recover the temperature correctly when used on mcfost+phantom dump, indicating temperatures of a few 1e6K for a protoplanetary disc.

### To Reproduce
See the data in the dropbox link below, and the following script

```python
"""Calculate vertical profile in discs."""

import matplotlib.pyplot as plt
import numpy as np
import plonk


def vertical_profile(snap, radius, vertical_height, radial_width=1):
    """Vertical profile at particular radius.

    Parameters
    ----------
    snap
        The Snap.
    radius
        The radius at which to calculate the vertical profile.
    vertical_height
        The height over which to compute the vertical profile.
    radial_width
        The radial width of the subset of particle on which to compute
        the vertical profile.
    """
    # Load extra quantities, e.g. cylindrical radius
    snap.extra_quantities()

    # Generate subsnap in a cylindrical ring
    subsnap = snap[
        (snap['R'] > radius - radial_width / 2)
        & (snap['R'] < radius + radial_width / 2)
    ]

    # Return Cartesian z-profile
    return plonk.load_profile(
        subsnap,
        ndim=1,
        coordinate='z',
        radius_min=-vertical_height / 2,
        radius_max=vertical_height / 2,
    )


if __name__ == '__main__':

    # Load snapshot
    snap = plonk.load_snap('hydrostatic_18790.h5')

    # Set molecular weight for temperature
    snap.set_molecular_weight(2.381)

    # Choose radii at which to calculate z-profiles.
    radius = np.linspace(25, 150, 5)

    # Vertical height
    R0 = 10  # reference radius
    H0 = 0.034 * R0  # scale height at reference
    q = 1 / 4  # sound speed index
    scale_height = H0 * (radius / R0) ** (3 / 2 - q)
    vertical_height = 10 * scale_height

    # Make figure and axes
    fig, axs = plt.subplots(ncols=2, figsize=(12, 5))
    axs[0].set(xlabel='altitude', ylabel='density')
    axs[1].set(xlabel='altitude', ylabel='temperature')

    # Loop over all radii and plot density and temperature profiles
    for R, dZ in zip(radius, vertical_height):
        prof = vertical_profile(snap=snap, radius=R, vertical_height=dZ)
        prof.plot('radius', 'density', label=f'radius={R:.0f}', ax=axs[0])
        prof.plot('radius', 'temperature', label=f'radius={R:.0f}', ax=axs[1])

    axs[1].legend().remove()
    plt.show()
```

### Expected behaviour
I would love to get the correct mcfost temperature ;-)

### Screenshots
<img width="1152" alt="Screen Shot 2020-07-29 at 17 42 25" src="https://user-images.githubusercontent.com/4163533/88771843-28b50000-d1c3-11ea-98b8-155f6b01f343.png">

### Environment (please complete the following information):

+ OS: MacOS 10.15.6
+ Python: python 3.7 (conda)
+ Plonk version: 0.5.3

### Data source
https://www.dropbox.com/sh/goc9rukjghnca0d/AAABP1n5N-iRlAukFkwUAAmda?dl=0

**Comment by dmentipl** [comment]
Hi @cpinte. Thanks very much for raising this bug.

I noticed that the snapshot file is missing the internal energy. Try the following:

```python
>>> import h5py
>>> f = h5py.File('hydrostatic_18790.h5', mode='r')
>>> list(f['particles'])
['divv', 'dt', 'h', 'itype', 'vxyz', 'xyz'] 
```

Is it converted from a standard Phantom file? Perhaps the converter has a bug.

**Comment by cpinte** [comment]
Yes, the dump was converted from a standard phatom dump via phantom2hdf5

**Comment by dmentipl** [comment]
Does the standard dump contain the internal energy?

**Comment by cpinte** [comment]
Yes, the internal is in the standard dump. I have added it to the dropbox directory.

**Comment by dmentipl** [comment]
I have added a bug fix in ddaaa1f that sets the pressure correctly from the internal energy if it's available. This should fix your issue as long as the internal energy is in the snapshot file. 

Hopefully we can fix this in Phantom soon. See the pull request at https://github.com/danieljprice/phantom/pull/39 for more.

**Comment by dmentipl** [comment]
Hi @cpinte, are you happy if I close this issue?

**Comment by cpinte** [comment]
Yes, it seems to work perfectly now.
