### ISSUE TITLE
[JOSS review] Example render usages

### ISSUE THREAD

**Issue by matthewturk** [dmentipl/plonk#4]
The documentation covers loading, and making basic renders, but requires some API exploration to determine how to use `render` to, for instance, visualize along a different axis.

Having in the docs examples that show rotating the snap, then `render`-ing the snap, would make this process more obvious.

**Comment by matthewturk** [comment]
https://github.com/openjournals/joss-reviews/issues/1884

**Comment by dmentipl** [comment]
Hi @matthewturk, sorry for the slow response.

I've added more detail to the documentation. And I've put up a larger data set at https://anaconda.org/dmentipl/plonk_example_data/.
