### ISSUE TITLE
Density plots appear unexpectedly fuzzy

### ISSUE THREAD

**Issue by becnealon** [dmentipl/plonk#5]
Column density plots in plonk don't appear to show the same information as in splash? I plotted a broken disc and it looked fuzzier than I thought it should and despite adjustments it didn't improve. Have I missed something? It appears that high density structure in the inner region and the gap between the inner and outer disc are not accurately reproduced in plonk? See the examples attached below.

[density_plonk.pdf](https://github.com/dmentipl/plonk/files/3912699/density_plonk.pdf)
[density_splash.pdf](https://github.com/dmentipl/plonk/files/3912703/density_splash.pdf)

Following the example in the wiki as much as possible, I plotted with:
viz = plonk.visualize.render(snap=snap,
                                 quantity='density',
                                 axis=axes,
                                 extent=[-15,15,-15,15],
                                 scalar_options={'cmap': 'gist_heat',
                                                            'norm': 'log',
                                                            'plot_colorbar': cbar}
                                 )

I'm using:
+ OS: macOS 10.13.6
+ Python: Python 3.7.3, Anaconda with conda 4.7.12, using Jupyter notebook
+ Plonk version: 0.2.1
+ SPH code: Phantom, version `c816ba88`, gas only simulation.

**Comment by dmentipl** [comment]
Hi @becnealon, thanks very much for the bug report.

It certainly looks like a bug. I'll have a look and get back to you.

**Comment by dmentipl** [comment]
I'm made some changes to the interpolation scheme that, I think, should fix your issue.

If you are happy to install Plonk from source (see https://github.com/dmentipl/plonk/blob/master/CONTRIBUTING.md) and can test with your data, that would be great. If not, and you're willing to share your snapshot with me, I can do the testing for you.

Please let me know how you'd like to proceed.

**Comment by becnealon** [comment]
Hi @dmentipl, yes I've tested this and it has fixed my problem. Thanks!
