### ISSUE TITLE
eccentricity function in profile.py 

### ISSUE THREAD

**Issue by cjfontec** [dmentipl/plonk#8]
### Describe the bug

In line 329 of profile.py, the definition of velocity reads:
`vel = self.Snap['vxyz'][self._mask]`
and it should be 
`vel = self.snap['vxyz'][self._mask]`

### To Reproduce
after loading a snapshot, running the following code results in an error

`prof = plonk.analysis.Profile(snap, radius_min=0, radius_max=6)`
`ecc = prof._profile_functions["eccentricity"](prof, gravitational_parameter = 2)`

### Expected behaviour

return radial profile of eccentricity

### Environment (please complete the following information):

+ OS: [macOS 10.14.6]
+ Python: [Python 3.7.3, Anaconda with conda 4.7.12, using Jupyter notebook]
+ Plonk version: [0.3.0]

**Comment by dmentipl** [comment]
Hi @cjfontec, thanks very much for the bug report.
